name: Movie Tracker Telegram

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours (at 00:00, 06:00, 12:00, 18:00 UTC)

  workflow_dispatch:  # Allows manual trigger

jobs:
  check_movies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python jolt.py  # Ensure your script is named correctly
